/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthModeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{id}/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemIntegrationsResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DevUserResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DevTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DevTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePersonRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    status?: components["schemas"]["LifecycleStatus"];
                    type?: components["schemas"]["SystemType"];
                    teamId?: string;
                    businessOwnerId?: string;
                    capabilityId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemListResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemWriteRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/parent-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    forSystemId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemRef"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemDetail"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemWriteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmSystemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    systemId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IntegrationDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IntegrationUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IntegrationDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IntegrationCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IntegrationDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data-objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataObjectDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDataObjectRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataObjectDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CapabilityTreeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities/couplings/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    dryRun?: boolean;
                    fingerprint?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "text/csv": string;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CapabilityImportResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities/couplings/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    dryRun?: boolean;
                    fingerprint?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "text/csv": string;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CouplingImportResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthModeResponse: {
            mode: string;
        };
        CapabilityChange: {
            kind: components["schemas"]["CapabilityChangeKind"];
            code: string;
            before: null | components["schemas"]["CapabilitySnapshot"];
            after: null | components["schemas"]["CapabilitySnapshot"];
            affectedSystems: components["schemas"]["CoupledSystem"][];
        };
        /** @enum {unknown} */
        CapabilityChangeKind: "Ny" | "Aendret" | "Slettes" | "Udgaar" | "Genaktiveres" | "FaarUnderkapabiliteter";
        CapabilityImportResult: {
            committed: boolean;
            errors: components["schemas"]["ImportRowError"][];
            summary: components["schemas"]["CapabilityImportSummary"];
            changes: components["schemas"]["CapabilityChange"][];
            fingerprint: null | string;
        };
        CapabilityImportSummary: {
            /** Format: int32 */
            new: number;
            /** Format: int32 */
            changed: number;
            /** Format: int32 */
            removed: number;
            /** Format: int32 */
            retired: number;
            /** Format: int32 */
            reactivated: number;
            /** Format: int32 */
            unchanged: number;
            /** Format: int32 */
            currentTotal: number;
            /** Format: int32 */
            removedFromMap: number;
            largeRemoval: boolean;
            /** Format: int32 */
            couplingsToMove: number;
            /** Format: int32 */
            systemsToMove: number;
        };
        CapabilityNode: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description: null | string;
            /** Format: uuid */
            parentId: null | string;
            /** Format: int32 */
            depth: number;
            path: string;
            selectable: boolean;
            overlap: null | components["schemas"]["CapabilityOverlap"];
        };
        CapabilityOverlap: {
            /** Format: int32 */
            counted: number;
            /** Format: int32 */
            planned: number;
            isOverlap: boolean;
            plannedOnTopOfActive: boolean;
            members: components["schemas"]["OverlapMember"][];
        };
        CapabilityRef: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            path: string;
            moveReason: null | components["schemas"]["MoveReason"];
        };
        CapabilitySnapshot: {
            code: string;
            name: string;
            parentCode: null | string;
            description: null | string;
        };
        CapabilityToMove: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            path: string;
            reason: components["schemas"]["MoveReason"];
            systems: components["schemas"]["CoupledSystem"][];
        };
        CapabilityTreeResponse: {
            items: components["schemas"]["CapabilityNode"][];
            toMove: components["schemas"]["CapabilityToMove"][];
            canImport: boolean;
            coverage: components["schemas"]["CouplingCoverage"];
        };
        ConfirmSystemRequest: {
            /** Format: uint32 */
            version: null | number;
        };
        CoupledSystem: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        CouplingChange: {
            kind: components["schemas"]["CouplingChangeKind"];
            system: components["schemas"]["CoupledSystem"];
            code: string;
            name: string;
            path: string;
            changedSinceExport: boolean;
        };
        /** @enum {unknown} */
        CouplingChangeKind: "Fjernes" | "Tilfoejes";
        CouplingCoverage: {
            /** Format: int32 */
            covered: number;
            /** Format: int32 */
            total: number;
        };
        CouplingImportResult: {
            committed: boolean;
            errors: components["schemas"]["ImportRowError"][];
            warnings: components["schemas"]["ImportRowError"][];
            summary: components["schemas"]["CouplingImportSummary"];
            changes: components["schemas"]["CouplingChange"][];
            notInFile: components["schemas"]["CoupledSystem"][];
            fingerprint: null | string;
        };
        CouplingImportSummary: {
            /** Format: int32 */
            systemsInFile: number;
            /** Format: int32 */
            systemsChanged: number;
            /** Format: int32 */
            added: number;
            /** Format: int32 */
            removed: number;
            /** Format: int32 */
            unchanged: number;
            /** Format: int32 */
            systemsCleared: number;
            largeRemoval: boolean;
            /** Format: int32 */
            systemsChangedSinceExport: number;
            /** Format: int32 */
            systemsNotInFile: number;
            /** Format: int32 */
            ignoredEdits: number;
        };
        CreateDataObjectRequest: {
            name: null | string;
        };
        CreatePersonRequest: {
            displayName: null | string;
            email: null | string;
            department: null | string;
        };
        DataObjectDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        DevTokenRequest: {
            userId: string;
        };
        DevTokenResponse: {
            accessToken: string;
        };
        DevUserResponse: {
            id: string;
            name: string;
            roles: string[];
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        ImportRowError: {
            /** Format: int32 */
            line: number;
            column: null | string;
            message: string;
        };
        IntegrationCreateRequest: {
            /** Format: uuid */
            fromSystemId: null | string;
            /** Format: uuid */
            toSystemId: null | string;
            /** Format: uuid */
            viaPlatformId: null | string;
            type: null | components["schemas"]["IntegrationType"];
            name: null | string;
            description: null | string;
            dataObjectIds: null | string[];
        };
        IntegrationDto: {
            /** Format: uuid */
            id: string;
            name: null | string;
            from: components["schemas"]["SystemLink"];
            to: components["schemas"]["SystemLink"];
            via: null | components["schemas"]["SystemLink"];
            type: null | components["schemas"]["IntegrationType"];
            description: null | string;
            dataObjects: components["schemas"]["DataObjectDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: uint32 */
            version: number;
            permissions: components["schemas"]["IntegrationPermissions"];
        };
        IntegrationPermissions: {
            canEdit: boolean;
        };
        /** @enum {unknown} */
        IntegrationRelation: "Ud" | "Via" | "Ind" | "Intern";
        IntegrationSummary: {
            /** Format: int32 */
            receivers: number;
            /** Format: int32 */
            suppliers: number;
            /** Format: int32 */
            viaPlatform: number;
            /** Format: int32 */
            localSolutions: number;
            /** Format: int32 */
            directDb: number;
        };
        /** @enum {unknown} */
        IntegrationType: "Api" | "Fil" | "Event" | "DirekteDb" | "Udtraek" | null;
        IntegrationUpdateRequest: {
            /** Format: uuid */
            viaPlatformId: null | string;
            type: null | components["schemas"]["IntegrationType"];
            name: null | string;
            description: null | string;
            dataObjectIds: null | string[];
            /** Format: uint32 */
            version: null | number;
        };
        /** @enum {unknown} */
        LifecycleStatus: "Planlagt" | "Indfases" | "IDrift" | "Udfases" | "Nedlagt";
        MePermissions: {
            canCreateSystems: boolean;
            canManagePersons: boolean;
            canManageDataObjects: boolean;
        };
        MeResponse: {
            oid: string;
            name: string;
            roles: string[];
            permissions: components["schemas"]["MePermissions"];
        };
        ModuleDto: {
            /** Format: uuid */
            id: string;
            name: string;
            lifecycleStatus: components["schemas"]["LifecycleStatus"];
        };
        /** @enum {unknown} */
        MoveReason: "Udgaaet" | "HarUnderkapabiliteter" | null;
        /** @enum {unknown} */
        OverlapExclusion: "Planlagt" | "Nedlagt" | "Udfases" | "LokalLoesning" | null;
        OverlapMember: {
            /** Format: uuid */
            id: string;
            name: string;
            exclusion: null | components["schemas"]["OverlapExclusion"];
        };
        PersonDto: {
            /** Format: uuid */
            id: string;
            displayName: string;
            email: null | string;
            department: null | string;
        };
        RoleAssignmentDto: {
            role: components["schemas"]["SystemRole"];
            person: components["schemas"]["PersonDto"];
        };
        RoleAssignmentInput: {
            role: components["schemas"]["SystemRole"];
            /** Format: uuid */
            personId: string;
        };
        SystemCapabilityDto: {
            capability: components["schemas"]["CapabilityRef"];
            heldBy: null | components["schemas"]["SystemRef"];
            overlap: null | components["schemas"]["CapabilityOverlap"];
            ownExclusion: null | components["schemas"]["OverlapExclusion"];
            sharedWith: components["schemas"]["OverlapMember"][];
        };
        SystemDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            aliases: string[];
            description: null | string;
            type: null | components["schemas"]["SystemType"];
            lifecycleStatus: components["schemas"]["LifecycleStatus"];
            managingTeam: null | components["schemas"]["TeamDto"];
            parent: null | components["schemas"]["SystemRef"];
            modules: components["schemas"]["ModuleDto"][];
            roles: components["schemas"]["RoleAssignmentDto"][];
            capabilities: components["schemas"]["SystemCapabilityDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            lastConfirmedAt: string;
            lastConfirmedByName: string;
            /** Format: uint32 */
            version: number;
            permissions: components["schemas"]["SystemPermissions"];
        };
        SystemIntegrationItem: {
            relation: components["schemas"]["IntegrationRelation"];
            counterpart: null | components["schemas"]["SystemLink"];
            localModule: null | components["schemas"]["SystemRef"];
            integration: components["schemas"]["IntegrationDto"];
        };
        SystemIntegrationsResponse: {
            summary: components["schemas"]["IntegrationSummary"];
            items: components["schemas"]["SystemIntegrationItem"][];
            canAdd: boolean;
        };
        SystemLink: {
            /** Format: uuid */
            id: string;
            name: string;
            parent: null | components["schemas"]["SystemRef"];
            type: null | components["schemas"]["SystemType"];
            lifecycleStatus: components["schemas"]["LifecycleStatus"];
        };
        SystemListItem: {
            /** Format: uuid */
            id: string;
            name: string;
            parent: null | components["schemas"]["SystemRef"];
            matchedAlias: null | string;
            type: null | components["schemas"]["SystemType"];
            lifecycleStatus: components["schemas"]["LifecycleStatus"];
            managingTeam: null | components["schemas"]["TeamDto"];
            businessOwner: null | components["schemas"]["PersonDto"];
            /** Format: date-time */
            lastConfirmedAt: string;
            /** Format: int32 */
            moduleCount: number;
        };
        SystemListResponse: {
            items: components["schemas"]["SystemListItem"][];
            /** Format: int32 */
            total: number;
        };
        SystemPermissions: {
            canEdit: boolean;
            canDelete: boolean;
            deleteBlockedReason: null | string;
            parentBlockedReason: null | string;
        };
        SystemRef: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** @enum {unknown} */
        SystemRole: "Forretningsejer" | "Systemejer" | "Systemforvalter";
        /** @enum {unknown} */
        SystemType: "Saas" | "Standardsystem" | "Egenudviklet" | "LowCode" | "Platform" | "LokalLoesning" | null;
        SystemWriteRequest: {
            name: null | string;
            aliases: null | string[];
            description: null | string;
            type: null | components["schemas"]["SystemType"];
            lifecycleStatus: null | components["schemas"]["LifecycleStatus"];
            /** Format: uuid */
            managingTeamId: null | string;
            /** Format: uuid */
            parentSystemId: null | string;
            roles: null | components["schemas"]["RoleAssignmentInput"][];
            /** Format: uint32 */
            version: null | number;
            capabilityIds?: null | string[];
        };
        TeamDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
