// <auto-generated />
using System;
using System.Collections.Generic;
using Ea.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ea.Api.Data.Migrations
{
    [DbContext(typeof(EaDbContext))]
    [Migration("20260924111027_Integrationer")]
    partial class Integrationer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ea")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ea.Api.Integrations.DataObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_normalized");

                    b.HasKey("Id")
                        .HasName("pk_data_objects");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_data_objects_name");

                    b.ToTable("data_objects", "ea");
                });

            modelBuilder.Entity("Ea.Api.Integrations.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_normalized");

                    b.Property<Guid>("SourceSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_system_id");

                    b.Property<Guid>("TargetSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_system_id");

                    b.Property<string>("Type")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("ViaPlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("via_platform_id");

                    b.HasKey("Id")
                        .HasName("pk_integrations");

                    b.HasIndex("TargetSystemId")
                        .HasDatabaseName("ix_integrations_target_system_id");

                    b.HasIndex("ViaPlatformId")
                        .HasDatabaseName("ix_integrations_via_platform_id");

                    b.HasIndex("SourceSystemId", "TargetSystemId", "Type", "ViaPlatformId", "NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_integrations_natural_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("SourceSystemId", "TargetSystemId", "Type", "ViaPlatformId", "NameNormalized"), false);

                    b.ToTable("integrations", "ea", t =>
                        {
                            t.HasCheckConstraint("ck_integrations_not_self", "source_system_id <> target_system_id");
                        });
                });

            modelBuilder.Entity("Ea.Api.Integrations.IntegrationDataObject", b =>
                {
                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<Guid>("DataObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_object_id");

                    b.HasKey("IntegrationId", "DataObjectId")
                        .HasName("pk_integration_data_objects");

                    b.HasIndex("DataObjectId")
                        .HasDatabaseName("ix_integration_data_objects_data_object_id");

                    b.ToTable("integration_data_objects", "ea");
                });

            modelBuilder.Entity("Ea.Api.Persons.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entra_object_id");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_entra_object_id");

                    b.ToTable("persons", "ea");
                });

            modelBuilder.Entity("Ea.Api.Systems.SystemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<string>("LastConfirmedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_confirmed_by_name");

                    b.Property<string>("LastConfirmedByOid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_confirmed_by_oid");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("lifecycle_status");

                    b.Property<Guid?>("ManagingTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("managing_team_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_normalized");

                    b.Property<Guid?>("ParentSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_system_id");

                    b.Property<string>("Type")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_systems");

                    b.HasIndex("ManagingTeamId")
                        .HasDatabaseName("ix_systems_managing_team_id");

                    b.HasIndex("ParentSystemId", "NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_systems_parent_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ParentSystemId", "NameNormalized"), false);

                    b.ToTable("systems", "ea");
                });

            modelBuilder.Entity("Ea.Api.Systems.SystemRoleAssignment", b =>
                {
                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.Property<string>("Role")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("SystemId", "Role", "PersonId")
                        .HasName("pk_system_roles");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_system_roles_person_id");

                    b.ToTable("system_roles", "ea");
                });

            modelBuilder.Entity("Ea.Api.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", "ea");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000001"),
                            Name = "Kerneapplikationer"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000002"),
                            Name = "Specialiserede Løsninger"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000003"),
                            Name = "Data & Integrationer"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000004"),
                            Name = "Digital Arbejdsplads"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000005"),
                            Name = "Stab"
                        });
                });

            modelBuilder.Entity("Ea.Api.Integrations.Integration", b =>
                {
                    b.HasOne("Ea.Api.Systems.SystemEntity", "SourceSystem")
                        .WithMany()
                        .HasForeignKey("SourceSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_integrations_systems_source_system_id");

                    b.HasOne("Ea.Api.Systems.SystemEntity", "TargetSystem")
                        .WithMany()
                        .HasForeignKey("TargetSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_integrations_systems_target_system_id");

                    b.HasOne("Ea.Api.Systems.SystemEntity", "ViaPlatform")
                        .WithMany()
                        .HasForeignKey("ViaPlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_integrations_systems_via_platform_id");

                    b.Navigation("SourceSystem");

                    b.Navigation("TargetSystem");

                    b.Navigation("ViaPlatform");
                });

            modelBuilder.Entity("Ea.Api.Integrations.IntegrationDataObject", b =>
                {
                    b.HasOne("Ea.Api.Integrations.DataObject", "DataObject")
                        .WithMany()
                        .HasForeignKey("DataObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_integration_data_objects_data_objects_data_object_id");

                    b.HasOne("Ea.Api.Integrations.Integration", null)
                        .WithMany("DataObjects")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_data_objects_integrations_integration_id");

                    b.Navigation("DataObject");
                });

            modelBuilder.Entity("Ea.Api.Systems.SystemEntity", b =>
                {
                    b.HasOne("Ea.Api.Teams.Team", "ManagingTeam")
                        .WithMany()
                        .HasForeignKey("ManagingTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_systems_teams_managing_team_id");

                    b.HasOne("Ea.Api.Systems.SystemEntity", "ParentSystem")
                        .WithMany("Modules")
                        .HasForeignKey("ParentSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_systems_systems_parent_system_id");

                    b.Navigation("ManagingTeam");

                    b.Navigation("ParentSystem");
                });

            modelBuilder.Entity("Ea.Api.Systems.SystemRoleAssignment", b =>
                {
                    b.HasOne("Ea.Api.Persons.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_system_roles_persons_person_id");

                    b.HasOne("Ea.Api.Systems.SystemEntity", null)
                        .WithMany("Roles")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_roles_systems_system_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Ea.Api.Integrations.Integration", b =>
                {
                    b.Navigation("DataObjects");
                });

            modelBuilder.Entity("Ea.Api.Systems.SystemEntity", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
